import { 
  Wifi, Waves, Car, Dumbbell, Wind, UtensilsCrossed, Eye, Shield, Coffee, Snowflake, Tv, Phone, BedDouble, Bath, Sparkles, Mountain, TreePine, Square, Compass, PawPrint, Flame, Gamepad, Shirt, Briefcase, Anchor, Palmtree, Activity, Laptop, Bike, Users,
  Monitor, Wine, GlassWater, Utensils, ChefHat, Bed, Baby, Accessibility, Ticket, Plane, Printer, Cigarette, CigaretteOff, Sun, Moon, Heart, VolumeX, Clock, Languages, DollarSign, Bell, Microwave, Tent, ArrowUpDown, WashingMachine, Volume2, Key, HelpCircle, Plug, Zap
} from "lucide-react";
import React from "react";

export const AMENITY_ICONS: Record<string, React.ComponentType<any>> = {
  // --- Core Comfort & Climate ---
  "Air conditioning": Wind,
  "Air Conditioning": Wind,
  "AC": Wind,
  "Heating": Flame,
  "Fan": Wind,
  "Soundproof room": VolumeX,
  "Soundproof Rooms": VolumeX,
  "Iron": Shirt,
  "Ironing facilities": Shirt,
  "Ironing Board": Shirt,
  "Ironing Service": Shirt,
  "Safe": Shield,
  "Safe Locker": Shield,
  "Safe Deposit Box": Shield,
  "In-room Safe": Shield,

  // --- Entertainment & Technology ---
  "TV": Tv,
  "Flat-screen TV": Monitor,
  "Smart TV": Tv,
  "Cable TV": Tv,
  "Satellite channels": Monitor,
  "Streaming service": Monitor,
  "Streaming Services": Monitor,
  "Streaming Services (Netflix/etc)": Monitor,
  "Telephone": Phone,
  "Free WiFi": Wifi,
  "WiFi": Wifi,
  "High-speed Internet": Wifi,

  // --- Refreshments & Kitchen ---
  "Coffee machine": Coffee,
  "Coffee Maker": Coffee,
  "Tea/Coffee maker": Coffee,
  "Electric Kettle": Coffee,
  "Minibar": GlassWater,
  "Mini Bar": GlassWater,
  "Refrigerator": Snowflake,
  "Microwave": Microwave,
  "Dining Area": UtensilsCrossed,
  "Dining Table": UtensilsCrossed,
  "Kitchenette": UtensilsCrossed,
  "Full Kitchen": UtensilsCrossed,
  "Washing Machine": WashingMachine,
  "Dryer": Shirt,

  // --- Bathroom & Hygiene ---
  "Bathrobe": BedDouble,
  "Bathrobes & Slippers": BedDouble,
  "Slippers": BedDouble,
  "Towels": BedDouble,
  "Toiletries": Bath,
  "Premium Toiletries": Bath,
  "Hot water": Bath,
  "Hot Water": Bath,
  "Bathtub": Bath,
  "Shower": Bath,
  "Rain Shower": Bath,
  "Attached bathroom": Bath,
  "Private Bathroom": Bath,
  "Shared Bathroom": Bath,
  "Toilet": Bath,
  "Cleaning products": Sparkles,
  "Hair dryer": Wind,
  "Hair Dryer": Wind,

  // --- Bed & Furniture ---
  "Wardrobe": BedDouble,
  "Desk": Laptop,
  "Work Desk": Laptop,
  "Sitting area": BedDouble,
  "Sofa": BedDouble,
  "Socket near bed": Plug,
  "King Bed": Bed,
  "Queen Bed": Bed,
  "Twin Beds": BedDouble,
  "Bunk Bed": Bed,
  "Extra Bed": Bed,
  "Baby Crib": Baby,

  // --- Dining & Food ---
  "Restaurant": UtensilsCrossed,
  "Cafe": Coffee,
  "Coffee Shop": Coffee,
  "Bar": Wine,
  "Pool Bar": Wine,
  "Snack Bar": Wine,
  "Lounge": Wine,
  "Breakfast Included": Utensils,
  "Buffet Breakfast": Utensils,
  "Continental Breakfast": Utensils,
  "American Breakfast": Utensils,
  "Asian Breakfast": Utensils,
  "Vegetarian Food": UtensilsCrossed,
  "Vegan Food": UtensilsCrossed,
  "Halal Food": UtensilsCrossed,
  "Kosher Food": UtensilsCrossed,
  "BBQ Facilities": Flame,
  "Private Dining": UtensilsCrossed,
  "Fine Dining": UtensilsCrossed,
  "Outdoor Dining": UtensilsCrossed,
  "24-Hour Room Service": UtensilsCrossed,
  "Room Service": UtensilsCrossed,

  // --- Wellness & Spa ---
  "Swimming Pool": Waves,
  "Outdoor Pool": Waves,
  "Indoor Pool": Waves,
  "Infinity Pool": Waves,
  "Kids Pool": Waves,
  "Private Pool": Waves,
  "Rooftop Pool": Waves,
  "Pool With View": Waves,
  "Children’s Pool": Waves,
  "Spa": Snowflake,
  "Sauna": Snowflake,
  "Steam Room": Snowflake,
  "Hot Tub": Bath,
  "Massage Center": Heart,
  "Wellness Center": Heart,
  "Yoga Room": Heart,
  "Meditation Area": Heart,
  "Fitness Center": Dumbbell,
  "Gym": Dumbbell,
  "Beauty Salon": Sparkles,

  // --- Outdoor & Leisure ---
  "Private Beach": Palmtree,
  "Beach Access": Palmtree,
  "Beachfront": Palmtree,
  "Garden": TreePine,
  "Picnic Area": TreePine,
  "Sun Terrace": Sun,
  "Sun Loungers": Sun,
  "Bonfire Area": Flame,
  "Camping Area": Tent,
  "Outdoor Fireplace": Flame,
  "Rooftop Lounge": Wine,
  "Game Room": Gamepad,
  "Indoor Games": Gamepad,
  "Outdoor Games": Gamepad,
  "Board Games": Gamepad,
  "Billiards": Gamepad,
  "Table Tennis": Gamepad,
  "Tennis Court": Dumbbell,
  "Badminton Court": Dumbbell,
  "Basketball Court": Dumbbell,
  "Volleyball Court": Dumbbell,
  "Golf Course": Dumbbell,
  "Mini Golf": Dumbbell,
  "Bowling": Dumbbell,
  "Cycling": Bike,
  "Bike Rental": Bike,
  "Hiking": Mountain,
  "Trekking": Mountain,
  "Horse Riding": Mountain,
  "Fishing": Anchor,
  "Boating": Anchor,
  "Kayaking": Anchor,
  "Water Sports": Waves,
  "Snorkeling": Anchor,
  "Scuba Diving": Anchor,
  "Surfing": Waves,
  "Skiing": Snowflake,
  "Karaoke": Gamepad,
  "Live Music": Sparkles,
  "DJ": Sparkles,
  "Nightclub": Moon,
  "Movie Screening": Tv,

  // --- Family & Kids ---
  "Family Rooms": Users,
  "Kids Play Area": Baby,
  "Kids Club": Users,
  "Kids Activities": Baby,
  "Babysitting": Baby,
  "Childcare": Baby,
  "Kids Meals": Baby,
  "High Chair": Baby,
  "Family Entertainment": Users,
  "Stroller Friendly": Accessibility,

  // --- Business & Events ---
  "Conference Hall": Briefcase,
  "Meeting Room": Briefcase,
  "Banquet Hall": Briefcase,
  "Business Center": Briefcase,
  "Coworking Space": Briefcase,
  "Event Space": Briefcase,
  "Wedding Hall": Briefcase,
  "Projector": Laptop,
  "Printer": Printer,
  "Fax Service": Laptop,
  "Whiteboard": Laptop,

  // --- Transportation & Parking ---
  "Free Parking": Car,
  "Private Parking": Car,
  "Paid Parking": Car,
  "Street Parking": Car,
  "Valet Parking": Car,
  "Accessible Parking": Car,
  "EV Charging Station": Zap,
  "Airport Shuttle": Plane,
  "Airport Pickup": Plane,
  "Airport Drop": Plane,
  "Shuttle Service": Car,
  "Taxi Service": Car,
  "Car Rental": Car,
  "Bicycle Parking": Bike,
  "Motorbike Rental": Bike,

  // --- Accessibility ---
  "Wheelchair Accessible": Accessibility,
  "Elevator": ArrowUpDown,
  "Ramp Access": Accessibility,
  "Braille Signage": Accessibility,
  "Visual Assistance": Accessibility,
  "Hearing Assistance": Accessibility,
  "Low Counter": Accessibility,
  "Emergency Cord Bathroom": Accessibility,
  "Accessible Room": Accessibility,

  // --- Guest Services ---
  "24-Hour Front Desk": Clock,
  "Express Check-In": Clock,
  "Express Check-Out": Clock,
  "Concierge": Users,
  "Luggage Storage": Briefcase,
  "Tour Desk": Compass,
  "Ticket Service": Ticket,
  "Wake-Up Service": Clock,
  "Currency Exchange": DollarSign,
  "ATM": DollarSign,
  "Multilingual Staff": Languages,
  "Guest Relations": Users,
  "Butler Service": Users,

  // --- Housekeeping ---
  "Daily Housekeeping": Sparkles,
  "Laundry": Shirt,
  "Dry Cleaning": Shirt,
  "Shoe Shine": Sparkles,
  "Trouser Press": Shirt,
  "Room Sanitization": Sparkles,
  "Linen Change": BedDouble,
  "Towel Change": BedDouble,

  // --- Safety & Security ---
  "24-Hour Security": Shield,
  "CCTV": Shield,
  "Security Guard": Shield,
  "Smoke Detector": Shield,
  "Fire Alarm": Bell,
  "Fire Extinguisher": Shield,
  "First Aid Kit": Activity,
  "Emergency Exit": Shield,
  "Key Card Access": Key,

  // --- Pet Friendly ---
  "Pet Friendly": PawPrint,
  "Pets Allowed": PawPrint,
  "Pet Bowls": PawPrint,
  "Pet Sitting": PawPrint,
  "Dog Walking Area": PawPrint,
  "Pet Grooming": PawPrint,

  // --- Specialized & Luxury ---
  "Luxury Suite": Sparkles,
  "Presidential Suite": Sparkles,
  "Villa": Mountain,
  "Private Villa": Mountain,
  "Honeymoon Suite": Heart,
  "Private Chef": ChefHat,
  "In-Room Spa": Snowflake,
  "Helipad": Plane,
  "Private Entrance": Key,
  "VIP Room Facilities": Sparkles,
  "Signature Experience": Sparkles,
  "Adults Only": Users,
  "Couple Friendly": Heart,
  "Smoking Rooms": Cigarette,
  "Non-Smoking Rooms": CigaretteOff,
  "Connecting Rooms": Key,
  "Lakefront": Waves,
  "River View": Waves,
  "Smart Room Controls": Laptop,
  "Voice Assistant Room": Laptop,
  "Digital Key Access": Key,
  "Self Check-In": Key,

  // --- Views ---
  "City view": Eye,
  "City View": Eye,
  "Garden view": TreePine,
  "Garden View": TreePine,
  "Pool view": Waves,
  "Pool View": Waves,
  "Sea view": Waves,
  "Sea View": Waves,
  "Ocean View": Waves,
  "Mountain view": Mountain,
  "Mountain View": Mountain,
  "Lake View": Waves,
  "Balcony": Square,
  "Terrace": TreePine,
  "Patio": Square,
  "Forest View": TreePine,
  "Hilltop Resort": Mountain,
};

// Helper function to get amenity icon with a case-insensitive fallback to HelpCircle
export const getAmenityIcon = (name: string): React.ComponentType<any> => {
  if (!name) return HelpCircle;
  const icon = AMENITY_ICONS[name];
  if (icon) return icon;
  
  // Fallback to case-insensitive match
  const key = Object.keys(AMENITY_ICONS).find(k => k.toLowerCase() === name.toLowerCase());
  return key ? AMENITY_ICONS[key] : HelpCircle;
};
